// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HarryPotter
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("EstimatePurchaseV4")]
    public partial class EstimatePurchaseV4Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EstimatePurchaseV4.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EstimatePurchaseV4", "\tIn order to buy harry potter books\r\n\tAs a customer\r\n\tI want to estimate the valu" +
                    "e of my purchase", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Estimate the value of three books of different volumes")]
        [NUnit.Framework.CategoryAttribute("V4")]
        public virtual void EstimateTheValueOfThreeBooksOfDifferentVolumes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Estimate the value of three books of different volumes", new string[] {
                        "V4"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("a basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price",
                        "Volume"});
            table1.AddRow(new string[] {
                        "8",
                        "1"});
            table1.AddRow(new string[] {
                        "8",
                        "2"});
            table1.AddRow(new string[] {
                        "8",
                        "2"});
#line 9
 testRunner.When("I buy books", ((string)(null)), table1, "When ");
#line 14
 testRunner.Then("the total is 23.199999999999999 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Estimate the value of 5 books forming 2 sets of different volumes")]
        [NUnit.Framework.CategoryAttribute("V4")]
        public virtual void EstimateTheValueOf5BooksForming2SetsOfDifferentVolumes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Estimate the value of 5 books forming 2 sets of different volumes", new string[] {
                        "V4"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("a basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price",
                        "Volume"});
            table2.AddRow(new string[] {
                        "8",
                        "1"});
            table2.AddRow(new string[] {
                        "8",
                        "2"});
            table2.AddRow(new string[] {
                        "8",
                        "3"});
            table2.AddRow(new string[] {
                        "8",
                        "2"});
            table2.AddRow(new string[] {
                        "8",
                        "3"});
#line 19
 testRunner.When("I buy books", ((string)(null)), table2, "When ");
#line 26
 testRunner.Then("the total is 36.799999999999997 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Estimate the value of 5 forming 3 sets of different volumes")]
        [NUnit.Framework.CategoryAttribute("V4")]
        public virtual void EstimateTheValueOf5Forming3SetsOfDifferentVolumes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Estimate the value of 5 forming 3 sets of different volumes", new string[] {
                        "V4"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("a basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Price",
                        "Volume"});
            table3.AddRow(new string[] {
                        "8",
                        "1"});
            table3.AddRow(new string[] {
                        "8",
                        "2"});
            table3.AddRow(new string[] {
                        "8",
                        "1"});
            table3.AddRow(new string[] {
                        "8",
                        "2"});
            table3.AddRow(new string[] {
                        "8",
                        "1"});
#line 31
 testRunner.When("I buy books", ((string)(null)), table3, "When ");
#line 38
 testRunner.Then("the total is 38.399999999999999 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
